import datetime
import os

import requests
import streamlit as st
from dotenv import load_dotenv

load_dotenv()

BASE_URL = os.getenv("BASE_URL", "http://localhost:8000")

st.set_page_config(
    page_title="Agentic Financial Copilot",
    page_icon="💰",
    layout="centered",
    initial_sidebar_state="expanded",
)

st.title("💰 Agentic Financial Information Copilot")

if "messages" not in st.session_state:
    st.session_state.messages = []

st.markdown(
    """
Ask questions about **stocks, companies, financial ratios, SEC filings, financial news,
FX conversion, or portfolio risk**.
"""
)

with st.sidebar:
    st.header("Example Questions")
    st.markdown(
        """
- Analyze AAPL stock performance.
- Compare MSFT and NVDA financial metrics.
- Calculate P/E ratio for price 180 and EPS 6.4.
- Convert 25000 USD to INR.
- Analyze portfolio: AAPL:40, MSFT:30, NVDA:30.
- Search uploaded filing documents for revenue risk.
"""
    )
    st.warning("For informational use only. Not investment advice.")

with st.form(key="finance_query_form", clear_on_submit=True):
    user_input = st.text_area(
        "User Input",
        placeholder="e.g. Compare Apple and Microsoft based on market cap, P/E ratio, revenue, latest news, and risk flags.",
        height=120,
    )
    submit_button = st.form_submit_button("Analyze")

if submit_button and user_input.strip():
    st.session_state.messages.append({"role": "user", "content": user_input})

    try:
        with st.spinner("Financial Copilot is analyzing..."):
            payload = {"question": user_input}
            response = requests.post(f"{BASE_URL}/query", json=payload, timeout=120)

        if response.status_code == 200:
            answer = response.json().get("answer", "No answer returned.")
            st.session_state.messages.append({"role": "assistant", "content": answer})

            markdown_content = f"""# 💰 Financial Copilot Report

**Generated:** {datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')}  
**Created by:** Agentic Financial Information Copilot

---

{answer}

---

*This output is generated by AI for financial information only. Verify all numbers and sources before making business or investment decisions.*
"""
            st.markdown(markdown_content)
        else:
            st.error("Copilot failed to respond: " + response.text)

    except Exception as exc:
        st.error(f"The response failed due to {exc}")

if st.session_state.messages:
    with st.expander("Conversation History"):
        for msg in st.session_state.messages:
            st.markdown(f"**{msg['role'].title()}:** {msg['content']}")
